In [1]:
import autoroot
from rs_tools._src.preprocessing.normalize import normalize

%matplotlib inline
%load_ext autoreload
%autoreload 2

/home/freischem/.conda/envs/rs_tools_iti/lib/python3.11/site-packages/goes2go/data.py:519: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  within=pd.to_timedelta(config["nearesttime"].get("within", "1H")),
/home/freischem/.conda/envs/rs_tools_iti/lib/python3.11/site-packages/goes2go/NEW.py:188: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  within=pd.to_timedelta(config["nearesttime"].get("within", "1H")),


In [1]:
import xarray as xr

norm_dir = '/home/freischem/outputs/miniset/20240517-0928/normalization'
goes_norm = xr.open_dataset(f'{norm_dir}/goes_norm.nc')

In [9]:
goes_norm['mean'].values, goes_norm['std'].values

(array([134.38202   ,  65.178566  ,  37.20662   ,   2.272993  ,
          5.744725  ,   1.5239868 ,   0.77519065,   2.815666  ,
          7.9387918 ,  13.896899  ,  47.947056  ,  43.477985  ,
         82.78253   ,  93.38069   , 100.64417   ,  88.33139   ],
       dtype=float32),
 array([83.57160446, 70.23925393, 47.01136956,  6.13335517,  6.55724009,
         1.74397223,  0.245557  ,  0.69149961,  1.84830359,  3.10537042,
        11.73538443,  8.68892694, 18.23192365, 20.14717129, 20.09120789,
        14.56906235]))

In [11]:
msg_norm = xr.open_dataset(f'{norm_dir}/msg_norm.nc')

In [13]:
msg_norm['mean'].values, msg_norm['std'].values

(array([ 1.695779 ,  0.6518643, 52.94932  , 45.511276 , 86.90486  ,
        97.99122  , 80.530754 ,  2.6322215,  2.830637 ,  3.2238169,
        14.109417 ], dtype=float32),
 array([ 1.65503616,  0.23466894, 15.14200648, 10.67773555, 22.5324939 ,
        23.94238188, 14.97517086,  2.73353005,  3.34456361,  0.8772509 ,
         3.74212206]))

In [3]:
import os
goes_files = os.listdir('/mnt/disks/data/miniset/goes16/geoprocessed/')
goes_files = ['/mnt/disks/data/miniset/goes16/geoprocessed/' + f for f in goes_files]

In [3]:
# f = goes_files[0].split('/')[-1]
# f

In [4]:
# ls /mnt/disks/data/miniset/goes16/geoprocessed/

In [5]:
# get_list_filenames('/mnt/disks/data/miniset/goes16/geoprocessed/', ext='nc')

In [6]:
# from iti.data.geo_utils import get_split, get_list_filenames


# splits_dict = { 
#     "train": {"years": [2020], "months": [10], "days": list(range(1,20))},
#     "val": {"years": [2020], "months": [10], "days": list(range(20,32))},
# }

# get_split(goes_files, splits_dict['train'])
    

# # def get_files(self):
# #     # Get filenames from data_dir
# #     files = get_list_filenames(data_path=self.data_dir, ext=self.ext)
# #     # split files based on split criteria
# #     files = get_split(files=files, split_dict=self.splits_dict)
# #     return files


In [4]:
import xarray as xr
# ds_goes_files = xr.open_mfdataset(goes_files[:100])


In [14]:
goes_time = xr.open_dataset(goes_files[1])

In [64]:
msg_time = xr.open_dataset(msg_files[1])


In [70]:
list(msg_time.band_wavelength.values)

[1.64, 3.92, 8.7, 9.66, 10.8, 12.0, 13.4, 0.64, 0.81, 6.25, 7.35]

In [5]:
ds_goes = normalize(goes_files[:10])

In [6]:
msg_files = os.listdir('/mnt/disks/data/miniset/msg/geoprocessed/')
msg_files = ['/mnt/disks/data/miniset/msg/geoprocessed/' + f for f in msg_files]

In [71]:
from iti.data.geo_editor import BandSelectionEditor


In [77]:
data_dict['data'].shape

(11, 1289, 891)

In [80]:
source_bands = data_dict["wavelengths"]
# Get indexes of bands to select
# indexes = [np.where(source_bands == wvl)[0][0] for wvl in target_bands]
for wvl in target_bands:
    print(np.where(source_bands == wvl)[0][0])

7


IndexError: index 0 is out of bounds for axis 0 with size 0

In [82]:
source_bands, wvl

(array([ 1.64,  3.92,  8.7 ,  9.66, 10.8 , 12.  , 13.4 ,  0.64,  0.81,
         6.25,  7.35]),
 3.89)

In [90]:
data = msg_time.Rad.compute().to_numpy()
target_bands=[0.64, 3.92, 7.35, 9.66, 13.4]
data_dict = {"data": data,
            "wavelengths" : msg_time.band_wavelength.compute().to_numpy()}
editor = BandSelectionEditor(target_bands=target_bands)
data_bands_order1=editor.call(data_dict=data_dict)



target_bands=[7.35, 9.66, 13.4, 0.64, 3.92]
data_dict = {"data": data,
            "wavelengths" : msg_time.band_wavelength.compute().to_numpy()}
editor = BandSelectionEditor(target_bands=target_bands)
data_bands_order2=editor.call(data_dict=data_dict)

In [93]:
import time
time.time()

1715683597.6426992

In [92]:
data_bands_order1['wavelengths'], data_bands_order2['wavelengths']

(array([ 0.64,  3.92,  7.35,  9.66, 13.4 ]),
 array([ 7.35,  9.66, 13.4 ,  0.64,  3.92]))

In [94]:
import wandb


In [95]:
logging_config = {}
wandb_id = logging_config['wandb_id'] if 'wandb_id' in logging_config else None
log_model = logging_config['wandb_log_model'] if 'wandb_log_model' in logging_config else False


In [97]:
run = wandb.init(project='msg-goes-miniset', 
                 name='wandb-test', 
                 entity='lilli-freischem', 
                 id=None, 
                 dir='/home/freischem/outputs/miniset/')

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: lilli-freischem. Use `wandb login --relogin` to force relogin
wandb: WARNING Path /home/freischem/outputs/miniset/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path /home/freischem/outputs/miniset/wandb/ wasn't writable, using system temp directory


In [117]:
from datetime import datetime
time_str = datetime.now().strftime("%Y%m%d-%H%M")
base_dir = '/home/freischem/outputs/miniset'

import os
os.path.join(base_dir, time_str)

'/home/freischem/outputs/miniset/20240514-1058'

In [101]:
from lightning.pytorch.loggers import WandbLogger


wandb_logger = WandbLogger(project='msg-goes-miniset', name='wandb-test', offline=True,
                           entity='lilli-freischem', id=None, dir='/home/freischem/outputs/miniset/', log_model=False)


In [105]:
# print(wandb_logger

In [119]:
from iti.data.editor import RandomPatchEditor

In [120]:
data = msg_time.Rad.compute().to_numpy()
target_bands=[0.64, 3.92, 7.35, 9.66, 13.4]
data_dict = {"data": data,
            "wavelengths" : msg_time.band_wavelength.compute().to_numpy()}
editor = BandSelectionEditor(target_bands=target_bands)
data_dict=editor.call(data_dict=data_dict)

editor = RandomPatchEditor(patch_shape=(256, 256))
patches=editor.call(data=data_dict['data'])


In [123]:
msg_time.Rad.shape, goes_time.Rad.shape

((11, 1289, 891), (16, 3687, 504))

In [125]:
msg_time

<xarray.Dataset> Size: 78MB
Dimensions:          (y: 1289, x: 891, band: 11, time: 1, band_wavelength: 11)
Coordinates:
  * y                (y) float64 10kB 0.0 3e+03 ... 3.862e+06 3.865e+06
  * x                (x) float64 7kB -4.264e+06 -4.261e+06 ... -1.593e+06
    cloud_mask       (y, x) float64 9MB ...
    latitude         (y, x) float64 9MB ...
    longitude        (y, x) float64 9MB ...
  * band             (band) <U6 264B 'IR_016' 'IR_039' ... 'WV_062' 'WV_073'
  * time             (time) <U19 76B '2020-10-21 14:00:00'
  * band_wavelength  (band_wavelength) float64 88B 1.64 3.92 8.7 ... 6.25 7.35
Data variables:
    Rad              (band, y, x) float32 51MB ...
Attributes:
    calibration:         radiance
    standard_name:       toa_outgoing_radiance_per_unit_wavenumber
    platform_name:       Meteosat-11
    sensor:              seviri
    units:               mW m-2 sr-1 (cm-1)-1
    orbital_parameters:  {"projection_longitude": 0.0, "projection_latitude":...

In [124]:
3687/1289

2.8603568657874323

In [122]:
patches.shape

(5, 256, 256)

In [86]:
data_bands["data"].shape, data_bands["wavelengths"].shape

((5, 1289, 891), (5,))

In [89]:
# data_bands["data"]

In [7]:
ds_msg = normalize(msg_files[:10])

In [8]:
ds_goes = ds_goes.compute()

In [9]:
ds_msg = ds_msg.compute()

In [12]:
ds_goes

<xarray.Dataset> Size: 272B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    mean             (band) float32 64B 144.0 74.45 43.39 ... 89.34 96.57 85.23
    std              (band) float64 128B 97.21 80.72 53.49 ... 23.48 23.76 17.25

In [18]:
from iti.data.editor import Editor

import numpy as np

class MeanStdNormEditor(Editor):
    """
    Normalise each band in the data using the mean and std from the norm_ds.
    """
    def __init__(self, norm_ds, key="data"):
        """
        Args:
            norm_ds (xarray.Dataset): Dataset with normalization values (mean and std)
            key (str): Key in dictionary to apply transformation
        """
        self.key = key
        self.norm = norm_ds

    def call(self, data_dict, **kwargs):
        data = data_dict[self.key]
        # use wavelengths and only normalise the bands that we have in the data
        data_wavelengths = data_dict["wavelengths"]
        # Get indeces of bands to select
        indeces = [np.where(self.norm.band_wavelength == wvl)[0][0] for wvl in data_wavelengths]
        
        # extract relevant means and stds
        means = self.norm['mean'][indeces].values
        stds = self.norm['std'][indeces].values

        # check that number of channels equals number of means & stds
        assert data.shape[0] == means.shape[0]
        assert data.shape[0] == stds.shape[0]

        # apply normalization
        data = (data - means[:, None, None]) / stds[:, None, None]
        
        # Update dictionary
        data_dict[self.key] = data
        return data_dict

In [62]:
goes_time

<xarray.Dataset> Size: 275MB
Dimensions:          (x: 504, y: 3687, time: 1, band_wavelength: 16, band: 16)
Coordinates:
  * x                (x) float32 2kB 3.108e+06 3.109e+06 ... 3.611e+06 3.612e+06
  * y                (y) float32 15kB 501.3 1.503e+03 ... 3.693e+06 3.694e+06
  * time             (time) <U16 64B '2020-10-26 14:05'
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
    latitude         (y, x) float64 15MB ...
    longitude        (y, x) float64 15MB ...
    cloud_mask       (y, x) float32 7MB ...
Data variables:
    Rad              (band, y, x) float32 119MB ...
    DQF              (band, y, x) float32 119MB ...
Attributes: (12/30)
    naming_authority:          gov.nesdis.noaa
    Conventions:               CF-1.7
    standard_name_vocabulary:  CF Standard Name Table (v35, 20 July 2016)
    institution:               DOC/NOAA/NESDIS > U.S. Department of Commerce,...
    project:                   GOES
    production_site:           WCDAS
    ...                        ...
    timeline_id:               ABI Mode 6
    date_created:              2020-10-26T14:09:56.5Z
    time_coverage_start:       2020-10-26T14:00:19.7Z
    time_coverage_end:         2020-10-26T14:09:50.5Z
    LUT_Filenames:             SpaceLookParams(FM1A_CDRL79RevP_PR_09_00_02)-6...
    id:                        fc5ae74c-413e-4ee6-8b54-bfd6d004f270

In [11]:
import numpy as np
data_wavelengths = np.array([0.47, 1.38,  1.61,])
indeces = [np.where(ds_goes.band_wavelength == wvl)[0][0] for wvl in data_wavelengths]

In [12]:
means = ds_goes['mean'][indeces].values
stds = ds_goes['std'][indeces].values

In [18]:
data = goes_time.Rad[indeces].compute().to_numpy()

In [61]:
data_norm = (data - means[:, None, None]) / stds[:, None, None]

np.isclose(((data[2] - means[2]) / stds[2]), data_norm[2]).all()

True

In [56]:
((data - means[:, None, None]) / stds[:, None, None])[0]

array([[-0.38646985, -0.53684598, -0.428241  , ..., -0.71228487,
        -0.7039306 , -0.67886792],
       [-0.31963594, -0.55355446, -0.64545097, ..., -0.6955764 ,
        -0.6955764 , -0.68722212],
       [-0.63709677, -0.59532561, -0.67051372, ..., -0.68722212,
        -0.6955764 , -0.68722212],
       ...,
       [-0.4198868 , -0.40317825, -0.23609364, ...,  0.47401596,
         0.42389061,  0.40718205],
       [-0.25280219, -0.12748873,  0.14820094, ...,  0.39047366,
         0.37376526,  0.43224481],
       [-0.25280219,  0.08972139,  0.23174324, ...,  0.32363975,
         0.39882785,  0.38211946]])

In [55]:
(data[0] - means[0]) / stds[0]

array([[-0.38646984, -0.536846  , -0.42824098, ..., -0.71228486,
        -0.7039306 , -0.67886794],
       [-0.31963593, -0.5535545 , -0.64545095, ..., -0.69557637,
        -0.69557637, -0.6872221 ],
       [-0.63709676, -0.5953256 , -0.6705137 , ..., -0.6872221 ,
        -0.69557637, -0.6872221 ],
       ...,
       [-0.4198868 , -0.40317824, -0.23609364, ...,  0.47401595,
         0.4238906 ,  0.40718204],
       [-0.2528022 , -0.12748873,  0.14820093, ...,  0.39047366,
         0.37376526,  0.4322448 ],
       [-0.2528022 ,  0.08972139,  0.23174325, ...,  0.32363975,
         0.39882785,  0.38211945]], dtype=float32)

In [52]:
(data - means[:, None, None]).shape, stds.shape

((3, 3687, 504), (3,))

In [47]:
((data[0] - means[0]) == (data - means[:, None, None])[0]).all(), ((data[2] - means[2]) == (data - means[:, None, None])[2]).all(), ((data[1] - means[1]) == (data - means[:, None, None])[1])[1:].all()

(True, True, True)

In [45]:
(data - means[:, None, None]) / stds[:, None, None]

array([[[-0.38646985, -0.53684598, -0.428241  , ..., -0.71228487,
         -0.7039306 , -0.67886792],
        [-0.31963594, -0.55355446, -0.64545097, ..., -0.6955764 ,
         -0.6955764 , -0.68722212],
        [-0.63709677, -0.59532561, -0.67051372, ..., -0.68722212,
         -0.6955764 , -0.68722212],
        ...,
        [-0.4198868 , -0.40317825, -0.23609364, ...,  0.47401596,
          0.42389061,  0.40718205],
        [-0.25280219, -0.12748873,  0.14820094, ...,  0.39047366,
          0.37376526,  0.43224481],
        [-0.25280219,  0.08972139,  0.23174324, ...,  0.32363975,
          0.39882785,  0.38211946]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [-0.41461605, -0.41461605, -0.41461605, ..., -0.41461605,
         -0.31526359, -0.31526359],
        [-0.41461605, -0.41461605, -0.41461605, ..., -0.31526359,
         -0.31526359, -0.31526359],
        ...,
        [-0.41461605, -0.41461605, -0.41461605, ..., -

In [38]:
((data[0] - means[0]) == (data - means[:, None, None])[0]).all(), ((data[2] - means[2]) == (data - means[:, None, None])[2]).all(), ((data[1] - means[1]) == (data - means[:, None, None])[1]).all()

(True, True, False)

In [43]:
((data[1] - means[1])[1:] == (data - means[:, None, None])[1][1:]).all()

True

In [41]:
(data[1] - means[1])

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [-3.389072 , -3.389072 , -3.389072 , ..., -3.389072 , -2.5769649,
        -2.5769649],
       [-3.389072 , -3.389072 , -3.389072 , ..., -2.5769649, -2.5769649,
        -2.5769649],
       ...,
       [-3.389072 , -3.389072 , -3.389072 , ..., -2.5769649, -2.5769649,
        -2.5769649],
       [-3.389072 , -3.389072 , -3.389072 , ..., -2.5769649, -2.5769649,
        -2.5769649],
       [-3.389072 , -3.389072 , -3.389072 , ..., -2.5769649, -2.5769649,
        -2.5769649]], dtype=float32)

In [24]:
data - means[:, None, None]

array([[[-37.568344  , -52.186256  , -41.628876  , ..., -69.24049   ,
         -68.42838   , -65.992065  ],
        [-31.071487  , -53.81047   , -62.743637  , ..., -67.61628   ,
         -67.61628   , -66.80417   ],
        [-61.931534  , -57.871002  , -65.17996   , ..., -66.80417   ,
         -67.61628   , -66.80417   ],
        ...,
        [-40.816772  , -39.19255   , -22.950424  , ...,  46.078613  ,
          41.20598   ,  39.581757  ],
        [-24.574646  , -12.393051  ,  14.406464  , ...,  37.95755   ,
          36.333344  ,  42.01808   ],
        [-24.574646  ,   8.721725  ,  22.527527  , ...,  31.460693  ,
          38.769653  ,  37.145447  ]],

       [[         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [ -3.389072  ,  -3.389072  ,  -3.389072  , ...,  -3.389072  ,
          -2.5769649 ,  -2.5769649 ],
        [ -3.389072  ,  -3.389072  ,  -3.389072  , ...,  -2.5769649 ,
          -2.5769649 ,  -2.5769649 ],
        ...,


In [21]:
data.shape[0] == means.shape[0]

True

In [55]:
stds

array([97.20899093,  8.17400094,  6.69193914])

In [30]:
data_wavelengths = np.array([0.47, 1.38,  1.61,])
indexes = [np.where(ds_goes.band_wavelength == wvl)[0][0] for wvl in data_wavelengths]
indexes

[0, 3, 4]

In [39]:
ds_goes.isel(band_wavelength = indexes)

<xarray.Dataset> Size: 220B
Dimensions:          (band_wavelength: 3, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 12B 0.47 1.38 1.61
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    mean             (band) float32 64B 144.0 74.45 43.39 ... 89.34 96.57 85.23
    std              (band) float64 128B 97.21 80.72 53.49 ... 23.48 23.76 17.25

In [26]:
np.where(np.array([0.47, 1.38,  1.61,]) == 0.47)

(array([0]),)

In [62]:
data = goes_time['Rad'][indeces]

In [10]:
ds_msg

<xarray.Dataset> Size: 484B
Dimensions:          (band: 11, band_wavelength: 11)
Coordinates:
  * band             (band) <U6 264B 'IR_016' 'IR_039' ... 'WV_062' 'WV_073'
  * band_wavelength  (band_wavelength) float64 88B 1.64 3.92 8.7 ... 6.25 7.35
Data variables:
    mean             (band) float32 44B 1.814 0.6359 51.78 ... 3.091 3.14 13.84
    std              (band) float64 88B 1.735 0.2418 16.02 ... 0.9149 3.935

In [19]:
9.5024524e+02

950.24524

In [9]:
ds_msg

<xarray.Dataset> Size: 440B
Dimensions:          (band: 11, band_wavelength: 11)
Coordinates:
  * band             (band) <U6 264B 'IR_016' 'IR_039' ... 'WV_062' 'WV_073'
  * band_wavelength  (band_wavelength) float64 88B 1.64 3.92 8.7 ... 6.25 7.35
Data variables:
    mean             (band) float32 44B 1.814 0.6359 51.78 ... 3.091 3.14 13.84
    std              (band) float32 44B 5.322 0.1253 417.6 ... 30.0 1.242 24.09

In [21]:
from typing import List
import xarray as xr
from pathlib import Path
from functools import partial


def spatial_mean(ds: xr.Dataset, spatial_variables: List[str]) -> xr.Dataset:
    return ds.mean(spatial_variables)


files = goes_files[:10]

temporal_variables = ["time"]
spatial_variables = ["x","y"]

preprocess_mean = partial(spatial_mean, spatial_variables=spatial_variables)

# calculate mean
ds_mean = xr.open_mfdataset(files, preprocess=preprocess_mean, combine="by_coords",  engine="netcdf4")

# ds_mean = ds_mean.mean(temporal_variables)

def preprocess_std(ds: xr.Dataset):
    # calculate the mean
    ds = ((ds - ds_mean)**2).std(spatial_variables)
    return ds


ds_std = xr.open_mfdataset(goes_files[:10], preprocess=preprocess_std, combine="by_coords",  engine="netcdf4")

# ds_std = ds_std.mean(temporal_variables)

In [31]:
goes_ds = xr.open_dataset(files[0])
goes_ds - ds_mean

<xarray.Dataset> Size: 275MB
Dimensions:          (x: 504, y: 3687, time: 1, band_wavelength: 16, band: 16)
Coordinates:
  * x                (x) float32 2kB 3.108e+06 3.109e+06 ... 3.611e+06 3.612e+06
  * y                (y) float32 15kB 501.3 1.503e+03 ... 3.693e+06 3.694e+06
  * time             (time) <U16 64B '2020-10-27 13:05'
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
    latitude         (y, x) float64 15MB ...
    longitude        (y, x) float64 15MB ...
    cloud_mask       (y, x) float32 7MB ...
Data variables:
    Rad              (band, y, x, time) float32 119MB -19.53 -13.84 ... -9.927
    DQF              (band, y, x, time) float32 119MB -0.0002013 ... 0.0

In [34]:
N = 504 * 3687

In [37]:
ds_test = ((goes_ds - ds_mean) ** 2).sum(['x','y']) / N
ds_test

<xarray.Dataset> Size: 400B
Dimensions:          (time: 1, band_wavelength: 16, band: 16)
Coordinates:
  * time             (time) <U16 64B '2020-10-27 13:05'
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    Rad              (band, time) float64 128B 7.591e+03 5.06e+03 ... 229.4
    DQF              (band, time) float64 128B 0.0004025 0.0 ... 0.0 0.0

In [51]:
ds = xr.open_dataset(files[0])
N = ds.x.size * ds.y.size

In [50]:
ds.x.size, ds.y.size

(504, 3687)

In [42]:
import numpy as np
np.sqrt(((goes_ds - ds_mean) ** 2).sum(['x','y']) / N)

<xarray.Dataset> Size: 400B
Dimensions:          (band: 16, time: 1, band_wavelength: 16)
Coordinates:
  * time             (time) <U16 64B '2020-10-27 13:05'
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    Rad              (band, time) float64 128B 87.13 71.13 46.68 ... 20.72 15.15
    DQF              (band, time) float64 128B 0.02006 0.0 0.006225 ... 0.0 0.0

In [25]:
ds_mean = ds_mean.compute()

In [24]:
ds_std = ds_std.compute()

In [27]:
ds_std.Rad.min(), ds_std.Rad.max()

(<xarray.DataArray 'Rad' ()> Size: 4B
 array(0.11369764, dtype=float32),
 <xarray.DataArray 'Rad' ()> Size: 4B
 array(35742.094, dtype=float32))

In [29]:
1.15231943e+04

11523.1943

In [28]:
ds_std

<xarray.Dataset> Size: 2kB
Dimensions:          (time: 10, band_wavelength: 16, band: 16)
Coordinates:
  * time             (time) <U16 640B '2020-10-07 17:05' ... '2020-10-30 15:05'
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    Rad              (band, time) float32 640B 1.152e+04 2.916e+04 ... 535.9
    DQF              (band, time) float32 640B 0.04563 0.2669 ... 0.0 0.0

In [37]:
ds_std = ds_std.rename({'Rad':'std'})
ds_mean = ds_mean.rename({'Rad':'mean'})

ValueError: cannot rename 'Rad' because it is not a variable or dimension in this dataset

In [48]:
ds_mean = ds_mean.drop_vars([])


In [49]:
ds_mean

<xarray.Dataset> Size: 144B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    mean             (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>

In [42]:
xr.combine_nested([ds_mean, ds_std], concat_dim='band')


<xarray.Dataset> Size: 480B
Dimensions:          (band_wavelength: 16, band: 32)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 32B 1 2 3 4 5 6 7 8 ... 9 10 11 12 13 14 15 16
Data variables:
    mean             (band) float32 128B dask.array<chunksize=(8,), meta=np.ndarray>
    std              (band) float32 128B dask.array<chunksize=(24,), meta=np.ndarray>
    DQF              (band) float32 128B dask.array<chunksize=(24,), meta=np.ndarray>

In [43]:
ds = xr.combine_by_coords([ds_mean, ds_std])

In [44]:
ds

<xarray.Dataset> Size: 272B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    std              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>
    DQF              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>
    mean             (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>

In [35]:
ds = ds_std.rename({'Rad':'std'})

ds = ds.assign(mean=ds_mean.Rad)
ds = ds.drop([v for v in ds.var() if v not in ['std', 'mean']])
ds

/var/tmp/ipykernel_17352/2147361793.py:3: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds = ds.drop([v for v in ds.var() if v not in ['std', 'mean']])


<xarray.Dataset> Size: 208B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    std              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>
    mean             (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>

In [34]:
ds.drop([v for v in ds.var() if v not in ['std', 'mean']])


/var/tmp/ipykernel_17352/846106241.py:1: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds.drop([v for v in ds.var() if v not in ['std', 'mean']])


<xarray.Dataset> Size: 208B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    std              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>
    mean             (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>

In [10]:
ds_std

<xarray.Dataset> Size: 208B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    Rad              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>
    DQF              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>

In [11]:
ds = xr.combine_by_coords([ds_mean, ds_std])

ValueError: Could not find any dimension coordinates to use to order the datasets for concatenation

In [16]:

import xarray as xr

In [37]:
from functools import partial
from typing import List

def spatial_mean(ds: xr.Dataset, spatial_variables: List[str]) -> xr.Dataset:
    return ds.mean(spatial_variables)

preprocess = partial(spatial_mean, spatial_variables=['x', 'y'])


In [40]:
ds_mean = xr.open_mfdataset(goes_files[:100], preprocess=preprocess, combine="by_coords",  engine="netcdf4")

In [44]:
ds_mean.mean(['time'])

<xarray.Dataset> Size: 208B
Dimensions:          (band_wavelength: 16, band: 16)
Coordinates:
  * band_wavelength  (band_wavelength) float32 64B 0.47 0.64 ... 12.27 13.27
  * band             (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Data variables:
    Rad              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>
    DQF              (band) float32 64B dask.array<chunksize=(8,), meta=np.ndarray>

In [32]:
ds = xr.open_mfdataset(goes_files, combine="by_coords",  engine="netcdf4")

In [35]:
ds.mean(['x', 'y']).mean(['time']).Rad

<xarray.DataArray 'Rad' (band: 16)> Size: 64B
dask.array<mean_agg-aggregate, shape=(16,), dtype=float32, chunksize=(8,), chunktype=numpy.ndarray>
Coordinates:
  * band     (band) int8 16B 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16